### ISSUE TITLE
NPM Deployment 

### ISSUE THREAD

**Issue by webysther** [gramps-project/Gramps.js#103]
I got this:

![image](https://user-images.githubusercontent.com/750007/189537801-a8bd6432-80e8-4a42-9925-26e41d44de4a.png)

When tried both in my dev and docker-compose:

```
npm install && npm run build
npm run start
```
OR
```
docker-compose
```

What is missing?

The [Deploying Gramps Web with Docker](https://gramps-project.github.io/web/Deployment/) also don't work.

**Comment by DavidMStraub** [comment]
Hi,

"don't work" is not a very helpful bug report. Are you running the frontend but not the backend? Did you follow [these instructions](https://gramps-project.github.io/web/dev-frontend/setup/) or something else?

**Comment by webysther** [comment]
Hi David, in the section "[Deploying Gramps Web with Docker](https://gramps-project.github.io/web/Deployment/)", access the link, please, I follow all steps, but I have the same error in detail, no working docker.

**Comment by DavidMStraub** [comment]
Ok I'd be happy to help but let me ask two things please. First, please open one issue per problem. The above with npm run start and deploying with Docker are obviously unrelated. Second, please state exactly which steps you took and which errors you see. Thanks.

**Comment by webysther** [comment]
With this steps:

```
npm install && npm run build
```
![image](https://user-images.githubusercontent.com/750007/189548291-2ec7a5ef-153f-4158-bb30-cbf75ce06315.png)

![image](https://user-images.githubusercontent.com/750007/189548306-db026d31-159c-4dda-9f74-fb3707556287.png)

`npm run start`

![image](https://user-images.githubusercontent.com/750007/189548333-045a665f-6403-447d-b1ff-e477f5ece271.png)

I got this:

![image](https://user-images.githubusercontent.com/750007/189548342-4e63ec07-3b0b-4f1c-ae7a-119e48b574fd.png)

**Comment by webysther** [comment]
Hi @DavidMStraub ok, sorry, now I get it. I will update the issue.

**Comment by DavidMStraub** [comment]
Ok - but are you running a backend at all? "No connection" means it doesn't find the backend.

**Comment by DavidMStraub** [comment]
If you want to run a backend manually, see [here](https://gramps-project.github.io/web/dev-backend/setup/). What are you actually trying to achieve? Frontend development or production deployment?

**Comment by webysther** [comment]
> If you want to run a backend manually, see [here](https://gramps-project.github.io/web/dev-backend/setup/). What are you actually trying to achieve? Frontend development or production deployment?

Production deployment on my own server (SSL, SQLite etc, etc). I prefer a one docker solution like is made by [LSO](https://www.linuxserver.io/), but works a docker-compose. I try the npm because docker failed and I suppose this problem of "No connection" is a undocumented need of a sqlite from gramps, I suppose.

**Comment by webysther** [comment]
I try to myself to figure out, but I find this docker-composer in the documentation:

```
version: "3.7"

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      TREE: "Gramps Web"  # will create a new tree if not exists
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
```

This docker-compose in the source code:

```
# docker-compose file for frontend development
# do not use in production!
# https://gramps-project.github.io/web/dev-frontend/setup/

version: "3.8"

services:
  gramps-proxy:
    image: nginx
    container_name: gramps-proxy-dev
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5555:80"
  gramps-api:
    container_name: gramps-api-dev
    build:
      context: ./dev
      dockerfile: Dockerfile.api
    volumes:
      - gramps_users:/app/users # persist user database
      - gramps_db:/root/.gramps/grampsdb # persist Gramps database
  gramps-frontend:
    container_name: gramps-frontend-dev
    build:
      context: .
      dockerfile: ./dev/Dockerfile.frontend
    volumes:
      - ./:/app

volumes:
  gramps_users:
  gramps_db:
```

And another different ones in your personal hub docker and inside /dev, so, I got very confused to be honest.
