### ISSUE TITLE
Can't send email | restore password

### ISSUE THREAD

**Issue by khashashin** [gramps-project/Gramps.js#144]
I'm getting error when trying to reset password:
```bash
[2022-11-26 15:15:24 +0000] [15] [ERROR] Error while trying to send e-mail.
```
My Project is running under Docker, with following `docker-compose.yml` file:
```yaml
version: "3.7"

services:
  grampsweb:
    container_name: family-tree
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "8686:5000"  # host:docker
    volumes:
      - /volume1/docker_data/gramps/gramps_users:/app/users  # persist user database
      - /volume1/docker_data/gramps/gramps_index:/app/indexdir  # persist search index
      - /volume1/docker_data/gramps/gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - /volume1/docker_data/gramps/gramps_secret:/app/secret  # persist flask secret
      - /volume1/docker_data/gramps/grampsdb:/root/.gramps/grampsdb  # persist Gramps database
      - /volume1/docker_data/gramps/gramps_media:/app/media  # persist media files
      - /volume1/docker_data/gramps/config.cfg:/app/config/config.cfg
```
And my config file:
```bash
TREE="Oramash"
BASE_URL="https://myowndomain.com"
SECRET_KEY="mysecretkey"
USER_DB_URI="sqlite:////app/users/users.sqlite"
MEDIA_BASE_DIR="/app/media"
SEARCH_INDEX_DIR="/app/indexdir"
STATIC_PATH="/app/static"
EMAIL_HOST="mail.myowndomain.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER="noreply@myowndomain.com"
EMAIL_HOST_PASSWORD="mailaddresspassword"
DEFAULT_FROM_EMAIL="noreply@myowndomain.com"
CORS_ORIGINS="myowndomain.com,ha.myowndomain.com,*.myowndomain.com"
```
How could I debug this issue to get more noisy output. I've actually tested that I can connect to the mail server using another client.
