### ISSUE TITLE
Unable to import .gramps

### ISSUE THREAD

**Issue by vulcanjedi** [gramps-project/Gramps.js#185]
I have filtered a small subset and full export.
I have been using GRAMPS Portable for years and long awaited web functionality.

I have 2 dozen docker containers running for 8 years...can get up to the /firstrun but after purging config dir and redo repeated attempts fail to import.
Then you can import after account registration at all?
Any help?

**Comment by vulcanjedi** [comment]
/docker# docker logs grampsweb
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
INFO:gramps_webapi:Rebuilding search index ...
INFO:gramps_webapi:Done building search index.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c89728e71264, empty message
INFO  [alembic.runtime.migration] Running upgrade c89728e71264 -> e5e738d09fa7, Added configuration table
[2023-02-26 03:21:55 +0000] [17] [INFO] Starting gunicorn 20.1.0
[2023-02-26 03:21:55 +0000] [17] [INFO] Listening at: http://0.0.0.0:5000 (17)
[2023-02-26 03:21:55 +0000] [17] [INFO] Using worker: sync
[2023-02-26 03:21:55 +0000] [18] [INFO] Booting worker with pid: 18
[2023-02-26 03:21:55 +0000] [19] [INFO] Booting worker with pid: 19
[2023-02-26 03:21:55 +0000] [21] [INFO] Booting worker with pid: 21
[2023-02-26 03:21:55 +0000] [23] [INFO] Booting worker with pid: 23
[2023-02-26 03:21:55 +0000] [25] [INFO] Booting worker with pid: 25
[2023-02-26 03:21:55 +0000] [26] [INFO] Booting worker with pid: 26
[2023-02-26 03:21:55 +0000] [28] [INFO] Booting worker with pid: 28
[2023-02-26 03:21:55 +0000] [30] [INFO] Booting worker with pid: 30
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
# docker logs grampsweb_redis
1:C 25 Feb 2023 15:31:21.531 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Feb 2023 15:31:21.531 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Feb 2023 15:31:21.531 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 25 Feb 2023 15:31:21.532 * monotonic clock: POSIX clock_gettime
1:M 25 Feb 2023 15:31:21.533 * Running mode=standalone, port=6379.
1:M 25 Feb 2023 15:31:21.533 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 25 Feb 2023 15:31:21.533 # Server initialized
1:M 25 Feb 2023 15:31:21.533 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 25 Feb 2023 15:31:21.533 * Ready to accept connections
1:M 25 Feb 2023 16:31:22.098 * 1 changes in 3600 seconds. Saving...
1:M 25 Feb 2023 16:31:22.098 * Background saving started by pid 16
16:C 25 Feb 2023 16:31:22.242 * DB saved on disk
16:C 25 Feb 2023 16:31:22.243 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 25 Feb 2023 16:31:22.299 * Background saving terminated with success
1:M 26 Feb 2023 03:00:13.477 * 1 changes in 3600 seconds. Saving...
1:M 26 Feb 2023 03:00:13.477 * Background saving started by pid 17
17:C 26 Feb 2023 03:00:13.608 * DB saved on disk
17:C 26 Feb 2023 03:00:13.609 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 26 Feb 2023 03:00:13.678 * Background saving terminated with success

**Comment by DavidMStraub** [comment]
Hi,

did you use a compose file from the docs? Which one? Can you post your config (with secrets redacted)?

**Comment by vulcanjedi** [comment]
My Gramps DB has about 260 people.
But even taking a filtered export of less 10 failed.
```

    grampsweb:  &grampsweb
      image: ghcr.io/gramps-project/grampsweb:latest
      container_name: grampsweb
      restart: always
      ports:
        - "5000:5000"  #host:docker
      environment:
        TREE:  "famTree"  # will create a new tree if not exists
#        BASE_URL:  "https://mytree.example.com"
#        SECRET_KEY:  "xxxxxxxxxxx"  # your secret key
#        EMAIL_HOST:  ""xxxxxxxxxxx"
#        EMAIL_PORT:  "###"
#        EMAIL_USE_TLS:  "True"
#        EMAIL_HOST_USER:  "xxxxxxxxxxx"
#        EMAIL_HOST_PASSWORD:  "xxxxxxxxxxx" # your SMTP password
#        DEFAULT_FROM_EMAIL:  "xxxxxxxxxxx"
        GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
        GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
        GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb_redis:6379/1"
#        GUNICORN_NUM_WORKERS: 2
      depends_on:
        - grampsweb_redis
      volumes:
        - ${DOCKER_CONFIG}/grampsweb/users:/app/users  # persist user database
        - ${DOCKER_CONFIG}/grampsweb/index:/app/indexdir  # persist search index
        - ${DOCKER_CONFIG}/grampsweb/thumb_cache:/app/thumbnail_cache  # persist thumbnails
        - ${DOCKER_CONFIG}/grampsweb/secret:/app/secret  # persist flask secret
        - ${DOCKER_CONFIG}/grampsweb/db:/root/.gramps/grampsdb  # persist Gramps database
        - ${DOCKER_CONFIG}/grampsweb/media:/app/media  # persist media files


    grampsweb_celery:
      <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
      container_name: grampsweb_celery
      depends_on:
        - grampsweb_redis
      command: celery -A gramps_webapi.celery worker --loglevel=INFO

    grampsweb_redis:
      image: redis:alpine
      container_name: grampsweb_redis
      restart: always

```
