### ISSUE TITLE
Some errors in developer console

### ISSUE THREAD

**Issue by alcaprar** [gramps-project/Gramps.js#287]
I just updated from version [`0.19.1`](https://github.com/gramps-project/Gramps.js/releases/tag/v0.19.1) to [`0.22.2`](https://github.com/gramps-project/Gramps.js/releases/tag/v0.22.2). I did that in steps, passing from [`0.20.2`](https://github.com/gramps-project/Gramps.js/releases/tag/v0.20.2) first, then [`0.21.1`](https://github.com/gramps-project/Gramps.js/releases/tag/v0.21.1).

I am now getting these errors in developer console and the loading is never stopping:
```
Uncaught (in promise) TypeError: this.homePersonDetails is undefined
```
and 
```
Uncaught TypeError: setting getter-only property "active"
```

**Comment by DavidMStraub** [comment]
Please provide more details about your setup, in particular versions of all components involved and mode of deployment.

**Comment by alcaprar** [comment]
I copied this from settings:

> Gramps 5.1.5
Gramps Web API 1.1.7
Gramps.js 0.22.2
locale: en
multi-tree: false
task queue: true

I use docker and this is the gramps part of my docker-compose:
```
grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:v0.22.2
    restart: always
    ports:
      - "5000:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - ./data/gramps/users:/app/users  # persist user database
      - ./data/gramps/index:/app/indexdir  # persist search index
      - ./data/gramps/thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - ./data/gramps/secret:/app/secret  # persist flask secret
      - ./data/gramps/db:/root/.gramps/grampsdb  # persist Gramps database
      - ./data/gramps/media:/app/media  # persist media files
      - ./data/gramps/tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always

```
