### ISSUE TITLE
docker image doesn't work

### ISSUE THREAD

**Issue by ulysses4ever** [gramps-project/Gramps.js#82]
Hello! Thanks a lot for the amazing project! I am really eager to try is out locally but having trouble with the docker image. Here's my `docker-compose.yml` (closely follows [the one in the docs](https://gramps-project.github.io/web/Deployment/)):
```
version: "3.7"

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "5000:5000"  # host:docker
    volumes:
      - /home/ulysses/gramps/gramps_users:/app/users  # persist user database
      - /home/ulysses/gramps/gramps_index:/app/indexdir  # persist search index
      - /home/ulysses/gramps/gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - /home/ulysses/gramps/gramps_secret:/app/secret/secret  # persist flask secret
      - /home/ulysses/gramps/gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - /home/ulysses/gramps/gramps_media:/app/media  # persist media files
```
 `docker-compose up -d` creates a container (and the directories) successfully but I get an error page (`Firefox can’t establish a connection to the server at 127.0.0.1:5000.`) and `docker ps` shows the STATUS of the container as constantly "Restarting". What am I doing wrong?
